### ISSUE TITLE
效果很赞，但存在一点Bug

### ISSUE THREAD

**Issue by Yellow5A5** [Chacojack/HiveLayoutManager#2]
增加多个item后，拖动界面时会crash～应该是回收逻辑上的问题。

09-24 19:43:00.111 27135-27135/jack.hive E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: jack.hive, PID: 27135
                                                           java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: ViewHolder{face30b position=63 id=-1, oldPos=-1, pLpos:-1 tmpDetached no parent}
                                                               at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5235)
                                                               at android.support.v7.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1198)
                                                               at android.support.v7.widget.RecyclerView.access$6400(RecyclerView.java:150)
                                                               at android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:10828)
                                                               at android.support.v7.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:11328)
                                                               at android.support.v7.widget.SimpleItemAnimator.dispatchAddFinished(SimpleItemAnimator.java:289)
                                                               at android.support.v7.widget.DefaultItemAnimator$5.onAnimationEnd(DefaultItemAnimator.java:242)
                                                               at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:47)
                                                               at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1114)
                                                               at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
                                                               at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
                                                               at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                               at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Chacojack** [comment]
谢谢提供。其实是添加和滚动同时进行，会出现这个bug。我刚刚修改了，你可以再试一下。
